Finished FloatingTelephoneButton
stephanvl/the-consultancy-firm pull request #63
Opened 2018-01-10 10:19 UTC by Sohaib98

2018-01-10 12:14 UTC, michaelvs97 requested changes
How did you think this was going to pass the review?

2018-01-11 17:50 UTC, sleeuwen requested changes

2018-01-16 14:56 UTC, sleeuwen requested changes

2018-01-17 10:34 UTC, sleeuwen approved these changes

2018-04-05 10:37 UTC, closed without merging